### PR TITLE
added kustomization file to generate configmaps for example dashboards

### PR DESCRIPTION
**Pull request by ehearneRedHat**
To test changes, run `./hack/quickstart-setup.sh` followed by `kubectl kustomize examples/dashboards/ | kubectl apply -f -` . 

Then, port forward grafana using [observability doc](https://github.com/Kuadrant/kuadrant-operator/tree/main/config/observability/README.md) and verify that the three sample dashboards App Developer Dashboard, Platform Engineer Dashboard and Business User Dashboard are in Grafana. 

Will follow up this PR with modifying the quickstart-setup.sh file to include the kustomize command mentioned above.

### CODE REVIEW

**Comment by david-martin** [comment]
@ehearneRedHat I think there are changes needed to the grafana deployment as well to mount the configmaps as volumes?

**Comment by ehearneRedHat** [comment]
> @ehearneRedHat I think there are changes needed to the grafana deployment as well to mount the configmaps as volumes?

You're right - I didn't add the necessary changes in `config/observability/grafana_deployment_patch.yaml` to mount the volumes. Thanks for spotting that! 

Taking a look... :)

**Comment by ehearneRedHat** [comment]
@david-martin changes look good to me locally. Feel free to review when you have the chance. Also, thanks for your assistance with this one. Much appreciated. :)

**Comment by david-martin** [comment]
Changes look good.
Tested locally with:

```shell
KUADRANT_REF=dashboard-examples-kustomization KUADRANT_ORG=ehearneRedHat ./hack/quickstart-setup.sh Re
```

The 3 dashboards show up in grafana as expected.

**Review by david-martin — APPROVED** [review]

**Pull request merged**
