### PR TITLE
istio-optional: iteration 2

### PR DESCRIPTION
**Pull request by eguzki**
Second iteration of the "Have Istio optional" story.

Basically, this is about making the `wasm` package not coupled with any gateway provider. Additionally, field indexers are declared globally at `main.go` instead of by some controller.

part of #325 

Depends on https://github.com/Kuadrant/kuadrant-operator/pull/645

### CODE REVIEW

**Comment by KevFan** [comment]
Initial scan looks good, but requires a rebase. I'll have a look again once PR has been rebased

**Comment by eguzki** [comment]
@KevFan rebased and conflicts fixed. Ready for a new review. 

Thanks

**Comment by eguzki** [comment]
This codecov report is not accurate

Screenshot 2024-06-10 at 11-32-32 Kuadrant_kuadrant-operator The Operator to install and manage the lifecycle of the Kuadrant components deployments

Looking at the codecov website, actually it is green

Screenshot 2024-06-10 at 11-33-33 Code coverage done right

**Review by KevFan — APPROVED** [review]
Changes looks good me to me 🏅

**Pull request merged**
