### PR TITLE
[wip] refactor: parrallel tests

### PR DESCRIPTION
**Pull request by KevFan**

### CODE REVIEW

**Comment by eguzki** [comment]
What is the reasoning for this refactor? This PR conflicts with a WIP test refactor I am doing for making room to onboard EnvoyGateway. Basically I am creating "istio tests", so we can later add "envoy gateway tests".

**Comment by KevFan** [comment]
> What is the reasoning for this refactor? This PR conflicts with a WIP test refactor I am doing for making room to onboard EnvoyGateway. Basically I am creating "istio tests", so we can later add "envoy gateway tests".

@eguzki Just seeing how easy / difficult it is to do this / what issues are there and to see if it's worth it generally (can be seen as part of https://github.com/Kuadrant/kuadrant-operator/issues/564). Not particularly looking to merge this soon if it's a concern

**Comment by eguzki** [comment]
I thought we had already did this parallel test thing, but it was on the limitador-operator https://github.com/Kuadrant/limitador-operator/pull/134. 

There is a big conflict with https://github.com/Kuadrant/kuadrant-operator/pull/645 but we will workout as needed. :+1:

**Comment by KevFan** [comment]
Closing this and opening up another PR since it's a big rebase

**Pull request closed without merging**
