### PR TITLE
Add informative message for podman cmd fail

### PR DESCRIPTION
**Pull request by david-martin**

### CODE REVIEW

**Review by jasonmadigan — APPROVED** [review]
LGTM

**Review by jasonmadigan — CHANGES_REQUESTED** [review]
Seeing an integration test error:

```bash
./utils/docker-network-ipaddresspool.sh kind /home/runner/work/kuadrant-operator/kuadrant-operator/bin/yq | kubectl apply -n metallb-system -f -
Error: error inspecting object: no such network kind
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
make[1]: *** [Makefile:433: install-metallb] Error 1
make[1]: Leaving directory '/home/runner/work/kuadrant-operator/kuadrant-operator'
make: *** [Makefile:378: test-env-setup] Error 2
```

**Comment by david-martin** [comment]
👀

**Comment by david-martin** [comment]
I'm going test something here as there's an oversight.

A successful run might look like this in the logs:

```
2024-04-11T11:13:33.6934626Z ./utils/docker-network-ipaddresspool.sh kind /home/runner/work/kuadrant-operator/kuadrant-operator/bin/yq | kubectl apply -n metallb-system -f -
2024-04-11T11:13:33.7755390Z Error: error inspecting object: no such network kind
2024-04-11T11:13:34.1944819Z ipaddresspool.metallb.io/kuadrant-local created
```

The`Error:` output is presumably output by the podman cmd to stderr. This seems to be fine.
The stdout from the script is what's then passed to `kubectl apply` i.e. the metallb IPAdderssPool yaml etc...

In the failure, the logs show this error in addition to above:

```
error: error validating "STDIN": error validating data: invalid object to validate; if you choose to ignore these errors, turn validation off with --validate=false
```
I believe that's because of the new echo statements added in this pr that output 'helpful' messages to stdout, which are then passed to `kubectl apply`

I've updated the PR to output the helpful messages to stderr instead.

**Review by jasonmadigan — APPROVED** [review]

**Pull request merged**
